### ISSUE TITLE
I can get VAC?

### ISSUE THREAD

**Issue by VetaLioSTV** [rossengeorgiev/dota2mod_manacost#6]
Hello,i used this mod half year ago and all was fine. Now,when i have been come here to update lastest version, i saw that **WARNING** in description :

> ! WARNING !
> 
> While the current method works, it has not been allowed explicitly. It's unlikely that you will get VAC, but there are no guarantees. Use at your own risk.

Can you explain please,someone who have installed that mode,got VAC or what? 
Thanks

**Comment by rossengeorgiev** [comment]
No one has reported getting VAC. The warning in place since a while back when Valve removed the standard ways to make client side mods. The current method is a hack, and does break certain things in the client such as guides. In my opinion is unlikely for Valve to VAC ban anyone using this mod alone. I have used it ever since its' inception and accept any potential risk. However, I can't provide the mod without being completely transparent on the matter.
